//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIFFB2JDF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""no"" ?>
<JMF xmlns=""http://www.CIP4.org/JDFSchema_1_1"" TimeStamp=""2017-02-04T20:22:59+02:00"" Version=""1.3"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xsi:type=""JMFRootMessage"">
  <Command ID=""m170204202259.143_000027"" Type=""PipeClose"" xsi:type=""CommandPipeClose"">
    <PipeParams PipeID=""MC_PIPE"" Status=""Completed"" UpdatedStatus=""Available""/>
  </Command>
</JMF>")]
        public string JobEnd {
            get {
                return ((string)(this["JobEnd"]));
            }
            set {
                this["JobEnd"] = value;
            }
        }
    }
}
