//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveWorks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActiveWorks.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавить несколько работ с FTP.
        /// </summary>
        internal static string AddJobFromFtp {
            get {
                return ResourceManager.GetString("AddJobFromFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавить заказ.
        /// </summary>
        internal static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to брак.
        /// </summary>
        internal static string Brak {
            get {
                return ResourceManager.GetString("Brak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в наличии.
        /// </summary>
        internal static string Broadly {
            get {
                return ResourceManager.GetString("Broadly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to наличка.
        /// </summary>
        internal static string Cache {
            get {
                return ResourceManager.GetString("Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подключение к базе данных.
        /// </summary>
        internal static string ConnectingToBase {
            get {
                return ResourceManager.GetString("ConnectingToBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подключение к MQ Rabbit.
        /// </summary>
        internal static string ConnectingToRabbitMQ {
            get {
                return ResourceManager.GetString("ConnectingToRabbitMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to создать новую папку.
        /// </summary>
        internal static string CreateNewDirectory {
            get {
                return ResourceManager.GetString("CreateNewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to создание отчета.
        /// </summary>
        internal static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to створити файл Prinect Signa.
        /// </summary>
        internal static string CreateSignaFile {
            get {
                return ResourceManager.GetString("CreateSignaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to заказчик.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to список заказчиков.
        /// </summary>
        internal static string CustomersList {
            get {
                return ResourceManager.GetString("CustomersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to описание.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на директорию выше.
        /// </summary>
        internal static string DirectoryUp {
            get {
                return ResourceManager.GetString("DirectoryUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось переименовать папку с заказом.
        /// </summary>
        internal static string ErrorCantRenameJobFolder {
            get {
                return ResourceManager.GetString("ErrorCantRenameJobFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проводник.
        /// </summary>
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        internal static string FileBrowserLoading {
            get {
                return ResourceManager.GetString("FileBrowserLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to имя файла.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to размер.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тип.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to фильтр.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поиск закончен.
        /// </summary>
        internal static string FindFinish {
            get {
                return ResourceManager.GetString("FindFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не удалось создать папку.
        /// </summary>
        internal static string FormAddWork_CheckCustomerPresent_Не_вдалося_створити_папку {
            get {
                return ResourceManager.GetString("FormAddWork_CheckCustomerPresent_Не_вдалося_створити_папку", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to форматы.
        /// </summary>
        internal static string Formats {
            get {
                return ResourceManager.GetString("Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveWorks.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пт.
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инициализация.
        /// </summary>
        internal static string Inizializing {
            get {
                return ResourceManager.GetString("Inizializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загрузка.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загрузка заказчиков.
        /// </summary>
        internal static string LoadingCustomers {
            get {
                return ResourceManager.GetString("LoadingCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загрузка работ.
        /// </summary>
        internal static string LoadingJobs {
            get {
                return ResourceManager.GetString("LoadingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загрузка журнала.
        /// </summary>
        internal static string LoadingJournal {
            get {
                return ResourceManager.GetString("LoadingJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загрузка пластин.
        /// </summary>
        internal static string LoadingPlates {
            get {
                return ResourceManager.GetString("LoadingPlates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загрузка плагинов.
        /// </summary>
        internal static string LoadingPlugins {
            get {
                return ResourceManager.GetString("LoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to загрузка пруфов.
        /// </summary>
        internal static string LoadingProofs {
            get {
                return ResourceManager.GetString("LoadingProofs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Письмо отправлено!.
        /// </summary>
        internal static string MailSend {
            get {
                return ResourceManager.GetString("MailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отправить уведомление по почте.
        /// </summary>
        internal static string MessageSendEmailToCustomer {
            get {
                return ResourceManager.GetString("MessageSendEmailToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер сообщений.
        /// </summary>
        internal static string MessageServer {
            get {
                return ResourceManager.GetString("MessageServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пн.
        /// </summary>
        internal static string Mo {
            get {
                return ResourceManager.GetString("Mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to заметки.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to открыть в проводнике.
        /// </summary>
        internal static string OpenInExplorer {
            get {
                return ResourceManager.GetString("OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to відкрити файл Prinect Signa.
        /// </summary>
        internal static string OpenSignaFile {
            get {
                return ResourceManager.GetString("OpenSignaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № заказа.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to остаток.
        /// </summary>
        internal static string Ostatok {
            get {
                return ResourceManager.GetString("Ostatok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to владелец.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to части.
        /// </summary>
        internal static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оплачено.
        /// </summary>
        internal static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to запланировано.
        /// </summary>
        internal static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to запланировано пластин.
        /// </summary>
        internal static string PlannedPlate {
            get {
                return ResourceManager.GetString("PlannedPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пластины.
        /// </summary>
        internal static string Plates {
            get {
                return ResourceManager.GetString("Plates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время вывода.
        /// </summary>
        internal static string PrintTime {
            get {
                return ResourceManager.GetString("PrintTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to прогресс.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметить работу как выполненную?.
        /// </summary>
        internal static string QuestionMarkJobAsFinish {
            get {
                return ResourceManager.GetString("QuestionMarkJobAsFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить уведомление заказчику о смене статуса заказа?.
        /// </summary>
        internal static string QuestionSendMessageToCustomerAboutChangeOrderStatus {
            get {
                return ResourceManager.GetString("QuestionSendMessageToCustomerAboutChangeOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        internal static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обновить.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to переименовать.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сб.
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поиск.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрано.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to показать/спрятать:.
        /// </summary>
        internal static string ShowHide {
            get {
                return ResourceManager.GetString("ShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to статус.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сумма.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вс.
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to чт.
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вт.
        /// </summary>
        internal static string Tu {
            get {
                return ResourceManager.GetString("Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ср.
        /// </summary>
        internal static string We {
            get {
                return ResourceManager.GetString("We", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вывод за неделю.
        /// </summary>
        internal static string WeekDraw {
            get {
                return ResourceManager.GetString("WeekDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
