//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProofFolder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/TetrisData.csdl|res://*/TetrisData.ssdl|res://*/TetrisData.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=server;initial catalog=TetrisNew;persist security info=True;user id=Evgeniy;password=12351;MultipleActiveResultSets=True;App=EntityFramework&quot;"" providerName=""System.Data.EntityClient""")]
        public string connStr {
            get {
                return ((string)(this["connStr"]));
            }
            set {
                this["connStr"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=server;Initial Catalog=TetrisNew;Persist Security Info=True;User ID=E" +
            "vgeniy;Password=12351")]
        public string TetrisNewConnectionString {
            get {
                return ((string)(this["TetrisNewConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=server;Initial Catalog=TetrisNew;Persist Security Info=True;User ID=O" +
            "ksana;Password=zaza")]
        public string TetrisNewConnectionString1 {
            get {
                return ((string)(this["TetrisNewConnectionString1"]));
            }
        }
    }
}
