//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveWorks.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profiles")]
        public string ProfilesPath {
            get {
                return ((string)(this["ProfilesPath"]));
            }
            set {
                this["ProfilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultProfile {
            get {
                return ((string)(this["DefaultProfile"]));
            }
            set {
                this["DefaultProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.4.1\r\n-----------------\r\n+ додав стандартні формати у діалог виставлення трім бо" +
            "ксів\r\n\r\n8.3.1\r\n-----------------\r\n+ можливість зберігати файли Signa Station у п" +
            "апці з замовленням\r\n+ Скидання положень вікон без перезапуску програми\r\n+ Зміни " +
            "в браузері без перезапуску програми\r\n\r\n\r\n8.0.0\r\n-----------------\r\nПерехід на ne" +
            "t 4.8 і mongodb 4.4. Несумісно з попередньою версією\r\n+ створення jpg прев\'ю з p" +
            "df\r\n+ видалення категорій у налаштуваннях\r\n\r\n7.8.10\r\n-----------------\r\n+ додав " +
            "\"Утиліти для PDF\" -> \"Розвернути сторінки на 90° дзеркально\". Непарні сторінки р" +
            "озветаються на 90° проти годинникової стрілки. Парні - за годинниковою стрілкою." +
            "\r\n+ при відправлені листа показує сумартий об\'єм вкладень\r\n\r\n\r\n7.6.10\r\n---------" +
            "--------\r\n+ додав генератор пустишок Pdf з тиражами для Signa. Викликається чере" +
            "з контекстне меню у браузері: \"Утиліти для PDF\" -> \"Створити \"пустишки\" з тиража" +
            "ми\"\r\n\r\n7.5.10\r\n------------------\r\n+ переробив фонові задачі.\r\n\r\n7.4.9\r\n--------" +
            "----------\r\n+ в PDF utils додав \"розділення файлу на обкладинку і блок\"\r\n\r\n7.4.8" +
            "\r\n------------------\r\n* при правому кліку у вікні з файлами, якщо нема активного" +
            " замовлення, вискакувала помилка\r\n\r\n7.4.7\r\n-------------------\r\n* зберігається і" +
            "сторія пошуку при перезапуску програми\r\n\r\n7.4.6\r\n-------------------\r\n* при вида" +
            "ленні файла, показує хто блокує файл.\r\n\r\n7.4.5\r\n--------------------\r\n+ перенесе" +
            "но у плагін RabbitMq\r\n* виправлено помилки з відправкою лишніх повідомлень через" +
            " RabbitMq\r\n\r\n7.3.3\r\n--------------------\r\n+ опція в налаштуваннях для конвертаці" +
            "ї в PDF. \r\n\r\n7.2.3\r\n---------------------\r\n+ при нажатому Shift примусово створю" +
            "ється новий шаблон для Signa\r\n\r\n7.1.3\r\n---------------------\r\n* не оновлювалось " +
            "кількість файлів при видаленні\r\n\r\n7.1.2\r\n---------------------\r\n* виправлено пом" +
            "илку з програванням звуків при нових файлах на ftp\r\n\r\n7.1.1\r\n-------------------" +
            "--\r\n* виправлено подвійний запуск додатків\r\n\r\n7.0.0 beta 37\r\n-------------------" +
            "--\r\n+ додана подія \"AvailableSound.Ftp_StopTimer\" для плагінів на FtpExplorer.Ti" +
            "merStop() \r\n\r\n7.0.0 beta 36\r\n---------------------\r\n+ додано можливість зупиняти" +
            " таймер автоматичної перевірки FTP із скрипта.\r\n  Викликається так: FtpExplorer." +
            "TimerStop()")]
        public string WhatNew {
            get {
                return ((string)(this["WhatNew"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VirtualScreenX {
            get {
                return ((int)(this["VirtualScreenX"]));
            }
            set {
                this["VirtualScreenX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VirtualScreenY {
            get {
                return ((int)(this["VirtualScreenY"]));
            }
            set {
                this["VirtualScreenY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VirtualScreenW {
            get {
                return ((int)(this["VirtualScreenW"]));
            }
            set {
                this["VirtualScreenW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VirtualScreenH {
            get {
                return ((int)(this["VirtualScreenH"]));
            }
            set {
                this["VirtualScreenH"] = value;
            }
        }
    }
}
