//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginMailAttachmentsToNextcloud.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginMailAttachmentsToNextcloud.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///    &lt;a href=&quot;{link}/download&quot;
        ///       style=&quot;color: rgb(15, 126, 219); font-family: &apos;Lucida Console&apos;, Courier, monospace; font-size: 18px;&quot;&gt;
        ///        {filename}
        ///    &lt;/a&gt;
        ///    &lt;span style=&quot;margin-left: 5px; font-family: &apos;Lucida Console&apos;, Courier, monospace; font-size: 18px; color: grey;&quot;&gt;
        ///        ({size})
        ///    &lt;/span&gt;
        ///    &lt;span&gt;
        ///
        ///        &lt;a href=&quot;{link}&quot;
        ///           style=&quot;color: rgb(15, 126, 219); font-family: &apos;Lucida Console&apos;, Courier, monospace; font-size: 14px;&quot;&gt;
        ///            відкрити в брауз [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shablon_attachment {
            get {
                return ResourceManager.GetString("shablon_attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;padding: 5px; background-color: rgb(200, 230, 230);&quot;&gt;
        ///&lt;div style=&quot;margin-bottom: 5px; font-family:&apos;Lucida Console&apos;, Courier, monospace; font-size:16px&quot;&gt;До цього повідомлення додано посилання:&lt;/div&gt;
        ///&lt;div style=&quot;background-color: rgb(255, 255, 255); padding: 5px;&quot;&gt;.
        /// </summary>
        internal static string shablon_begin {
            get {
                return ResourceManager.GetString("shablon_begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///&lt;div style=&quot;color: rgb(68, 68, 68);text-align: right;font-family:&apos;Lucida Console&apos;, Courier, monospace; font-size: 12px; margin-top:10px;&quot;&gt;Автоматично додано плагіном для ActiveWorks 7&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string shablon_end {
            get {
                return ResourceManager.GetString("shablon_end", resourceCulture);
            }
        }
    }
}
